#!/usr/bin/env bash

DOTS_INSTALL_DIR="${HOME}/apps/dotfiles"

dots_install_git_bash() {
    local GIT_COMPLETION_URL="https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash"
    local GIT_COMPLETION_FILE_NAME=".bash_git_completion"
    local GIT_PROMPT_URL="https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh"
    local GIT_PROMPT_FILE_NAME=".bash_git_prompt"
    echo "=> Installing Git Completion..."
    curl "${GIT_COMPLETION_URL}" > "${HOME}/${GIT_COMPLETION_FILE_NAME}"

    echo "=> Installing Git Prompt"
    curl "${GIT_PROMPT_URL}" > "${HOME}/${GIT_PROMPT_FILE_NAME}"
}

dots_symlink_home() {
    local FILE_DIR="${1}"
    local FILE_NAME="${2}"
    if [[ -e "${HOME}/${FILE_NAME}" ]]; then
        echo "=> rm -rf ${HOME}/${FILE_NAME}"
        rm -rf "${HOME}/${FILE_NAME}"
    fi
    echo "=> ln -s ${FILE_DIR}/${FILE_NAME} ${HOME}/${FILE_NAME}"
    ln -s "${FILE_DIR}/${FILE_NAME}" "${HOME}/${FILE_NAME}"
}

dots_bash_exit_message() {
    echo "=========================================="
    echo "="
    echo "=Open new terminal for file to take effect"
    echo "="
    echo "=========================================="
}

dots_install_bash() {
    local BASH_FILE_DIR="${DOTS_INSTALL_DIR}/bash"
    for FILE in $(ls -A "${BASH_FILE_DIR}"); do
        dots_symlink_home "${BASH_FILE_DIR}" "${FILE}"
    done
    dots_install_git_bash
    dots_bash_exit_message
}

dots_confirm_bash() {
    echo "===================================="
    echo "=>"
    echo "=>WARNING! \nYOU WILL OVERWRITE CURRENT DOT FILES!"
    echo "=>"
    echo -e "=> Continue (yes/no)? \c"
    read INPUT
    if [[ "${INPUT}" = "yes" ]] || [[ "${INPUT}" = "Yes" ]] || [[ "${INPUT}" = "y" ]]; then
        echo "yes"
    else
        exit
    fi
}

dots_apps_install() {
    local APP_NAME="${1}.sh"
    local APP_DIR="${DOTS_INSTALL_DIR}/apps/"
    local APP_PATH="${APP_DIR}${APP_NAME}"

    if [[ -f "${APP_PATH}" ]]; then
        source "${APP_PATH}"
    fi
}

dots_config_install() {
    local CONFIG_NAME="${1}"
    local CONFIG_OPTION="${2:-"default"}"
    local CONFIG_DIR="${DOTS_INSTALL_DIR}/configs/"
    local CONFIG_PATH="${CONFIG_DIR}${CONFIG_NAME}"
    if [[ -e "${CONFIG_PATH}" ]]; then
        dots_symlink_home "${CONFIG_DIR}" "${CONFIG_NAME}"
    fi
    if [[ "${CONFIG_NAME}" = ".i3" ]]; then
        echo "=> ln -sf ${CONFIG_PATH}/config.${CONFIG_OPTION} ${CONFIG_PATH}/config"
        ln -sf "${CONFIG_PATH}/config.${CONFIG_OPTION}" "${CONFIG_PATH}/config"
    fi
}

if [[ "${1}" = "bash" ]]; then
    dots_confirm_bash
    dots_install_bash
fi

if [[ "${1}" = "apps" && -n "${2}" ]]; then
    echo "args ${1} ${2}"
    dots_apps_install "${2}"
fi

if [[ "${1}" = "config" && -n "${2}" ]]; then
    echo "args ${1} ${2} ${3}"
    dots_config_install "${2}" "${3}"
fi

if [[ "${1}" = "update" ]]; then
    echo "args ${1}"
    curl -o- https://gitlab.com/Reyco/dotfiles/raw/master/install.sh | bash
fi