#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset
# set -o xtrace

main() {

    local DOTS_GIT_SOURCE="https://github.com/rcodonnell/dotfiles.git"
    local DOTS_GIT_RELEASE_BRANCH="convert-dots-to-application"
    local DOTS_INSTALL_DIR="${HOME}/.dotfiles"
    local DOTS_BIN_DIR="${HOME}/bin"
    local DOTS_APP_FILENAME="dots"

    dots_has() {
        type "$1" > /dev/null 2>&1
    }

    dots_download_from_git() {
        echo "... Downloading dotfiles from git"
        if [[ -d "${DOTS_INSTALL_DIR}/.git" ]]; then
            echo "... Dots already installed in ${DOTS_INSTALL_DIR}"
        else
            mkdir -p "${DOTS_INSTALL_DIR}"
            command git clone "${DOTS_GIT_SOURCE}" -b "${DOTS_GIT_RELEASE_BRANCH}" --depth=1 "${DOTS_INSTALL_DIR}" || {
                echo >&2 'Failed to clone dotfile repo.'
                exit 1
            }
            command git --git-dir="${DOTS_INSTALL_DIR}"/.git --work-tree="${DOTS_INSTALL_DIR}" checkout -f --quiet "${DOTS_GIT_RELEASE_BRANCH}"
        fi
    }

    dots_symlink_to_bin() {
        echo "... Symlinking dotfile script to bin folder"
        mkdir -p "${DOTS_BIN_DIR}"

        if [ -L "${DOTS_BIN_DIR}/${DOTS_APP_FILENAME}" ]; then
            echo "... Dots script already linked"
        else
            ln -s "${DOTS_INSTALL_DIR}/${DOTS_APP_FILENAME}" "${DOTS_BIN_DIR}/${DOTS_APP_FILENAME}"
        fi
    }

    dots_install() {
        if dots_has git; then
            dots_download_from_git
        else
            echo >&2 'You need git to install dots'
            exit 1
        fi
        # dots_symlink_to_bin
    }
    rm -rf "${HOME}/.dotfiles" #TODO remove line
    dots_install
    source "${DOTS_INSTALL_DIR}/${DOTS_APP_FILENAME}"
}

main
