#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset
# set -o xtrace

main() {

    dots_has() {
        type "$1" > /dev/null 2>&1
    }

    dots_install_dir() {
        echo "${HOME}/.dotfiles"
    }

    dots_source() {
        local DOTS_SOURCE_URL
        DOTS_SOURCE_URL= 'https://github.com/rcodonnell/dotfiles.git'
        echo "${DOTS_SOURCE_URL}"
    }

    dots_install_from_git() {
        local INSTALL_DIR

        INSTALL_DIR="$(dots_install_dir)"

        if [[ -d "${INSTALL_DIR}/.git"]]; then
            echo "Dots already installed in ${INSTALL_DIR}"
        else
            mkdir -p "${INSTALL_DIR}"

        fi
    }

    dots_install() {
        if dots_has git; then
            dots_install_from_git
        else
            echo >&2 'You need git to install dots'
            exit 1
        fi
    }

    dots_install
}

main
