#!/usr/bin/env bash
alt - h : yabai -m window --focus west
alt - k : yabai -m window --focus north
alt - j : yabai -m window --focus south
alt - l : yabai -m window --focus east

shift + alt - h : yabai -m window --warp west
shift + alt - j : yabai -m window --warp south 
shift + alt - k : yabai -m window --warp north 
shift + alt - l : yabai -m window --warp east 

alt - v : yabai -m window --toggle split

shift + alt - right : yabai -m space --rotate 90
shift + alt - left : yabai -m space --rotate 270

# Kill container
alt + shift - q : skhd --key "cmd - q"
alt - q : skhd --key "cmd - q"

# Open terminal
alt - return: /Applications/kitty.app/Contents/MacOS/kitty --single-instance -d ~

# Restart Yabai
shift + alt - r : \
    /usr/bin/env osascript <<< \
        "display notification \"Restarting Yabai\" with title \"Yabai\""; \
    launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"


# alt - 1 : yabai -m window --display 1 yabai -m display --focus 1
# alt - 2 : yabai -m window --display 2 yabai -m display --focus 2
# alt - 3 : yabai -m window --display 3 yabai -m display --focus 3

# shift + alt - 1 : yabai -m space --focus 1
# shift + alt - 2 : yabai -m space --focus 2
# shift + alt - 3 : yabai -m space --focus 3
# shift + alt - 4 : yabai -m space --focus 4
# shift + alt - 5 : yabai -m space --focus 5
# shift + alt - 6 : yabai -m space --focus 6
# shift + alt - 7 : yabai -m space --focus 7
# shift + alt - 8 : yabai -m space --focus 8
# shift + alt - 9 : yabai -m space --focus 9
# shift + alt - 0 : yabai -m space --focus 10

# increase window size
# shift + alt - h : yabai -m window --resize left:-20:0
# shift + alt - h : yabai -m window --resize left:-20:0
# shift + alt - w : yabai -m window --resize top:0:-20

# decrease window size
# shift + cmd - s : yabai -m window --resize bottom:0:-20
# shift + cmd - w : yabai -m window --resize top:0:20

## increase window size
# shift + alt - h : yabai -m window --resize left:-20:0
# shift + alt - j : yabai -m window --resize bottom:0:20
# shift + alt - k : yabai -m window --resize top:0:-20
# shift + alt - l : yabai -m window --resize right:20:0

## decrease window size
# ctrl + alt - h : yabai -m window --resize left:20:0
# ctrl + alt - j : yabai -m window --resize bottom:0:-20
# ctrl + alt - k : yabai -m window --resize top:0:20
# ctrl + alt - l : yabai -m window --resize right:-20:0
#
# alt + return : open /Applications/iTerm.app/
# alt + enter : open /Applications/iTerm.app/
# alt - return : open /Applications/iTerm.app/


# set focus on space change
# alt + cmd - 1 : yabai -m display --focus $(yabai -m query --displays --space 1 | jq '.index'); skhd -k "ctrl - 1"
# alt + cmd - 2 : yabai -m display --focus $(yabai -m query --displays --space 2 | jq '.index'); skhd -k "ctrl - 2"

# move window to space
# shift + alt + cmd - 1 : yabai -m window --space 1; skhd -k "alt + cmd - 1"
# shift + alt + cmd - 2 : yabai -m window --space 2; skhd -k "alt + cmd - 2"

